### ISSUE TITLE
Wildlife Spotter Tab

### ISSUE THREAD

**Issue by RhiannonStephens** [zaxen/volunteer-portal#1]
Move the Wildlife Spotter tab to between Expeditions and Tutorials tab
![image](https://user-images.githubusercontent.com/10238220/32635884-44b19ffa-c606-11e7-8a5e-72b716a3288e.png)

**Comment by zaxen** [comment]
@RhiannonStephens should be done and on dev now

**Comment by RhiannonStephens** [comment]
Cool! I will close it
