### ISSUE TITLE
Wildlife Spotter front page

### ISSUE THREAD

**Issue by RhiannonStephens** [zaxen/volunteer-portal#2]
Need to replace
![image](https://user-images.githubusercontent.com/10238220/32637033-a91b1750-c60b-11e7-830a-711461ec91e1.png)
with
![image](https://user-images.githubusercontent.com/10238220/32637051-b8bc6e84-c60b-11e7-8a23-f9fd70f79e1e.png)
Do you have this?

**Comment by RhiannonStephens** [comment]
Sorry just realised I can do this myself

**Comment by sbearcsiro** [comment]
If you remove the text and image in the wildlife spotter landing page that text and that image are the defaults.
